Import('pluginenv', 'build_plugin')

localenv = pluginenv.Clone()

if localenv['GTK3']:
    localenv.Append(CCFLAGS=' `pkg-config --cflags gtk+-3.0` ')
    localenv.Append(LINKFLAGS=' `pkg-config --libs gtk+-3.0` ')
    files = ["Lfo.cpp"]
    build_plugin(localenv, "lunar_lfo", files)
             
